### ISSUE TITLE
How to make/edit addons

### ISSUE THREAD

**Issue by CristianEduardMihai** [AlfredoSequeida/karen#2]
I want to make karen speak romanian, for that i know i have to make my own addons or edit the pre-made addons. I have tried to do so with the datetime one:
config.json 
```
{
  "name": "datetime",
  "developer": "Alfredo Sequeida",
  "version": "0.0.1",
  "commands": [
    "cât e ceasul",
    "cât e ceasu",
    "în ce dată sunt",
    "în ce dată suntem",
    "cât e data",
    "în ce zi suntem",
    "cât e ziua"
  ],
  "icon": "icon.png",
  "entry-point": "datetime",
  "languages": [
    "ro"
  ],
  "upstream": "https://github.com/AlfredoSequeida/datetime"
}
```
datetime.py
```
from datetime import date, datetime

today = date.today()
now = datetime.now()


def say_time(voice_instance):
    current_time = now.strftime("%I:%M %p")
    voice_instance.say(current_time)


def say_date(voice_instance):
    date = today.strftime("%B %d %Y")
    voice_instance.say(date)


def say_day(voice_instance):
    day = today.strftime("%A")
    voice_instance.say(day)


def parse_query(command):
    query = ""

    if "ceasul" or "ceasu" in command:
        query = "time"
    elif "dată" in command:
        query = "date"
    elif "zi" or "ziua" in command:
        query = "day"

    return query


def execute_query(query, voice_instance):
    actions = {
        "time": say_time,
        "date": say_date,
        "day": say_day,
    }

    actions[query](voice_instance)


def run(command, args, voice_instance):
    query = parse_query(command)
    execute_query(query, voice_instance)
```
But i still get this error:
```
You said karen cât e ceasul
kevin has not been called
Executing cât e ceasul
Traceback (most recent call last):
  File "Karen.py", line 168, in <module>
    karen.run()
  File "Karen.py", line 152, in run
    self.execute_command(command)
  File "Karen.py", line 85, in execute_command
    f"{ADDONS_DIR}.{addon['developer']}_{addon['name']}.{addon['entry-point']}",
TypeError: 'module' object is not subscriptable
```
What did i do wrong ? Is there a tutorial on how to make addons ?

**Comment by CristianEduardMihai** [comment]
@AlfredoSequeida helped me by giving this link: https://alfredo.lol/karen/docs/0.0.1

**Comment by AlfredoSequeida** [comment]
@CristianEduardMihai  As a quick heads up, Karen has prebuilt functionality to speak different languages. You don't need to create an addon for it.

If you look at the config file
```
{
  "settings": {
    "names": [
      "karen",
      "kevin"
    ],
    "lang": "en"
  },
  "addons": []
}
```

there is an option called `lang` that option can be changed to `ro` to make Karen speak in Romanian. This will change the language of the entire system. For all addons as long as the add-on supports that specific language.

**Comment by Akul2010** [comment]
the docs dont work

**Comment by CristianEduardMihai** [comment]
> the docs dont work

Yea.. alfredo.lol is down.

**Comment by CristianEduardMihai** [comment]
> the docs dont work

I can help you understand the addon structure if you want. It's actually easy. Automated my whole home with karen

**Comment by Akul2010** [comment]
yes, please do. ive emailed alfredo if he could, by any chance, provide me the website and api code as well

**Comment by CristianEduardMihai** [comment]
> yes, please do. ive emailed alfredo if he could, by any chance, provide me the website and api code as well

There is no website or API, you just use an existing addon as a template

**Comment by Akul2010** [comment]
> > yes, please do. ive emailed alfredo if he could, by any chance, provide me the website and api code as well
> 
> There is no website or API, you just use an existing addon as a template

no, i meant the website with the docs

**Comment by CristianEduardMihai** [comment]
> > > yes, please do. ive emailed alfredo if he could, by any chance, provide me the website and api code as well
> > 
> > 
> > There is no website or API, you just use an existing addon as a template
> 
> no, i meant the website with the docs

It's down unfortunately

**Comment by Akul2010** [comment]
yeah, can you please help with the skills? thanks!

**Comment by CristianEduardMihai** [comment]
> yeah, can you please help with the skills? thanks!

The best way of understanding it is to take an already existing addon and try to modifi it
You need to add entries in config.json. the code in your .py file will be executed every time one is detected, and you'll have variables for the command and arguments

**Comment by Akul2010** [comment]
thanks! i got it now!

**Comment by AlfredoSequeida** [comment]
@Akul2010 @CristianEduardMihai Yeah sorry about the docs being down, unfortunately, I didn't justify keeping the site up and with it went the docs. I made a repo for the Karen website codebase including the docs and the API for @Akul2010 . Here are the docs: https://github.com/AlfredoSequeida/KarenBackend/blob/main/karen/templates/karen/docs-0.0.1.html
