### ISSUE TITLE
Source code for website and api

### ISSUE THREAD

**Issue by Akul2010** [AlfredoSequeida/karen#3]
Hey, I've been trying to create this for a long time now, is it possible you could give me the website and API for the addon manager and docs too? I would like to expand on what you have made so far.

**Comment by AlfredoSequeida** [comment]
@Akul2010 Sorry for the wait, I've seen your emails, but have been very busy lately, I made a repo for the website Karen codebase: https://github.com/AlfredoSequeida/KarenBackend
